version: '3'
services:
  stub:
    image: nginx:1.13.9-alpine
    volumes:
      - ./docker/stub-nginx-files:/usr/share/nginx/html:ro

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 8080:3000
    volumes:
      - .:/myapp
    depends_on:
      - stub
